
package com.seec.insurance.life.illustrationinquiry.ws;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebService(name = "IllustrationInquiryWS", targetNamespace = "http://ws.illustrationinquiry.life.insurance.seec.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IllustrationInquiryWS {


    /**
     * 
     * @param txlifeRequest
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "processIllustrationInquiryReturn", targetNamespace = "")
    @RequestWrapper(localName = "processIllustrationInquiry", targetNamespace = "http://ws.illustrationinquiry.life.insurance.seec.com", className = "com.seec.insurance.life.illustrationinquiry.ws.ProcessIllustrationInquiry")
    @ResponseWrapper(localName = "processIllustrationInquiryResponse", targetNamespace = "http://ws.illustrationinquiry.life.insurance.seec.com", className = "com.seec.insurance.life.illustrationinquiry.ws.ProcessIllustrationInquiryResponse")
    public String processIllustrationInquiry(
        @WebParam(name = "txlifeRequest", targetNamespace = "")
        String txlifeRequest);

}
