
package com.seec.insurance.life.illustrationinquiry.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "IllustrationInquiryWSService", targetNamespace = "http://ws.illustrationinquiry.life.insurance.seec.com", wsdlLocation = "file:/C:/Prashanta/Workspace/EBS-DTS-Service/R1690/Release/releaseFT6-Release1690/soap-webapplication/src/main/resources/Illustration.wsdl")
public class IllustrationInquiryWSService
    extends Service
{

    private static final URL ILLUSTRATIONINQUIRYWSSERVICE_WSDL_LOCATION;
    private static final WebServiceException ILLUSTRATIONINQUIRYWSSERVICE_EXCEPTION;
    private static final QName ILLUSTRATIONINQUIRYWSSERVICE_QNAME = new QName("http://ws.illustrationinquiry.life.insurance.seec.com", "IllustrationInquiryWSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Prashanta/Workspace/EBS-DTS-Service/R1690/Release/releaseFT6-Release1690/soap-webapplication/src/main/resources/Illustration.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ILLUSTRATIONINQUIRYWSSERVICE_WSDL_LOCATION = url;
        ILLUSTRATIONINQUIRYWSSERVICE_EXCEPTION = e;
    }

    public IllustrationInquiryWSService() {
        super(__getWsdlLocation(), ILLUSTRATIONINQUIRYWSSERVICE_QNAME);
    }

    public IllustrationInquiryWSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ILLUSTRATIONINQUIRYWSSERVICE_QNAME, features);
    }

    public IllustrationInquiryWSService(URL wsdlLocation) {
        super(wsdlLocation, ILLUSTRATIONINQUIRYWSSERVICE_QNAME);
    }

    public IllustrationInquiryWSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ILLUSTRATIONINQUIRYWSSERVICE_QNAME, features);
    }

    public IllustrationInquiryWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IllustrationInquiryWSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IllustrationInquiryWS
     */
    @WebEndpoint(name = "IllustrationInquiryWS")
    public IllustrationInquiryWS getIllustrationInquiryWS() {
        return super.getPort(new QName("http://ws.illustrationinquiry.life.insurance.seec.com", "IllustrationInquiryWS"), IllustrationInquiryWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IllustrationInquiryWS
     */
    @WebEndpoint(name = "IllustrationInquiryWS")
    public IllustrationInquiryWS getIllustrationInquiryWS(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.illustrationinquiry.life.insurance.seec.com", "IllustrationInquiryWS"), IllustrationInquiryWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ILLUSTRATIONINQUIRYWSSERVICE_EXCEPTION!= null) {
            throw ILLUSTRATIONINQUIRYWSSERVICE_EXCEPTION;
        }
        return ILLUSTRATIONINQUIRYWSSERVICE_WSDL_LOCATION;
    }

}
