//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.08.16 at 06:02:51 pm BST 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://beans.illustrationinquiry.life.insurance.seec.com", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.seec.insurance.life.illustrationinquiry.beans;
